# Generated by Django 3.0 on 2019-12-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_mentee_url', models.CharField(default=None, max_length=200)),
                ('title', models.CharField(default=None, max_length=500)),
                ('text_content', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(default=None, max_length=200)),
                ('quote', models.CharField(default=None, max_length=200)),
                ('img_mentee_url', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(default=None, max_length=200)),
                ('jabatan', models.CharField(default=None, max_length=200)),
                ('experience', models.IntegerField(default=0)),
                ('quote', models.CharField(default=None, max_length=200)),
                ('img_mentor_url', models.CharField(default=None, max_length=200)),
            ],
        ),
    ]
