# Generated by Django 3.0 on 2019-12-10 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_alterra', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='img_mentee_url',
            new_name='img_blog_url',
        ),
    ]
