# Generated by Django 3.0 on 2019-12-11 03:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_alterra', '0007_auto_20191210_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_post',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 11, 3, 53, 53, 635559)),
        ),
    ]
